name:  Deploy model Azure Machine Learning job
on:
  workflow_dispatch:
env:
  RESOURCE_GROUP: rg-dp100-labs
  WORKSPACE_NAME: mlw-dp100-labs
jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: install az ml extension
      run: az extension add -n ml -y        
    - name: register model
      run: |
        MODEL_PATH=$(az ml job list --query "[0].outputs.default.path" --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME --output tsv)
        echo "PATH is $MODEL_PATH"
        
        MODEL_NAME=$(az ml job list --query "[0].name" --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME --output tsv)
        echo "MODEL_NAME is $MODEL_NAME"
        
        MODEL_PATH=$(echo "azureml://jobs/$MODEL_NAME/outputs/artifacts/paths/model")
        echo "MODEL_PATH is $MODEL_PATH"
        
        az ml model create --type "mlflow_model" --name $MODEL_NAME --path $MODEL_PATH --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
    - name: create online endpoint
      run: |
        cat <<EOF | tee create-endpoint.yml
        \$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
        name: mlflow-endpoint
        auth_mode: key
        EOF
        az ml online-endpoint create --name diabetes-mlflow -f ./create-endpoint.yml --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
    
