name:  Deploy model Azure Machine Learning job
on:
  workflow_dispatch:
env:
  RESOURCE_GROUP: rg-dp100-labs
  WORKSPACE_NAME: mlw-dp100-labs
jobs:
  deploy-model:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: install az ml extension
      run: az extension add -n ml -y        
    - name: register model
      id: register
      run: |
        MODEL_PATH=$(az ml job list --query "[0].outputs.default.path" --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME --output tsv)
        echo "PATH is $MODEL_PATH"
        
        MODEL_NAME=$(az ml job list --query "[0].name" --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME --output tsv)
        echo "MODEL_NAME is $MODEL_NAME"
        
        MODEL_PATH=$(echo "azureml://jobs/$MODEL_NAME/outputs/artifacts/paths/model")
        echo "MODEL_PATH is $MODEL_PATH"
        
        echo "MODEL_NAME=$MODEL_NAME" >> $GITHUB_OUTPUT
        echo "MODEL_PATH=$MODEL_PATH" >> $GITHUB_OUTPUT

        az ml model create --type "mlflow_model" --name $MODEL_NAME --path $MODEL_PATH --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
    - name: create online endpoint
      id: endpoint
      run: |
        UUID=$(uuidgen | tr -d 'd' | head -c 8)
        echo "UUID=$UUID" >> $GITHUB_OUTPUT

        cat <<EOF | tee create-endpoint.yml
        \$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineEndpoint.schema.json
        name: mlflow-endpoint-$UUID
        auth_mode: key
        EOF

        az ml online-endpoint create --name mlflow-endpoint-$UUID -f ./create-endpoint.yml --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
    - name: deploy model
      run: |
        UUID=${{ steps.endpoint.outputs.UUID }}
        MODEL_NAME=${{ steps.register.outputs.MODEL_NAME }}
        MODEL_VERSION=$(az ml model list --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME --name $MODEL_NAME --query "[0].version" -o tsv)
        
        cat <<EOF | tee mlflow-deployment.yml
        \$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
        name: mlflow-deployment
        endpoint_name: mlflow-endpoint-$UUID
        model: azureml:$MODEL_NAME:$MODEL_VERSION
        instance_type: Standard_DS3_v2
        instance_count: 3
        EOF
        
        az ml online-deployment create --file mlflow-deployment.yml --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME

      
      

