name:  Automated trigger an Azure Machine Learning job
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - src/**
env:
  RESOURCE_GROUP: rg-dp100-labs
  WORKSPACE_NAME: mlw-dp100-labs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: install az ml extension
      run: az extension add -n ml -y        
    - name: setup
      run: az ml job create --file job.yml --resource-group $RESOURCE_GROUP --workspace-name $WORKSPACE_NAME
      working-directory: src
